import editAddress from '../support/pageObjects/editAddress';

describe('Edit Address Validation', () => {
  beforeEach(() => {
    cy.visit('')
    cy.loginEdit('kelompok_8@gmail.com', 'Sanbercodekelompok8')
    editAddress.clickDropDown()
    editAddress.clickMyAccount()
    editAddress.textAddressBook()
    editAddress.clickEditAddress()
  });

  it('Edit Address Success', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName()
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.verifySuccess('You saved the address.')
  });
  
  it('Edit Address First Name Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.ClearFirstName()
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorFirstName('This is a required field.')
  });
  
  it('Edit Address Last Name Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName()
    editAddress.ClearLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorLastName('This is a required field.')
  });
  
  it('Edit Address Company Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.ClearCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.verifySuccess('You saved the address.')
  });
  
  it('Edit Address Phone Number Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.ClearTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorTelephone('This is a required field.')
  });
  
  it('Edit Address Street Address Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.ClearStreet1()
    editAddress.ClearStreet2()
    editAddress.ClearStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorStreet1('This is a required field.')
  });

  it('Edit Address City Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.ClearCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorCity('This is a required field.')
  });

  it('Edit Address State/Province Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.ClearRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.verifySuccess('You saved the address.')
  });

  it('Edit Address Zip/Postal Code more than 5 - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.MoreThanZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.verifySuccess('You saved the address.')
  });

  it('Edit Address Zip/Postal Code Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.ClearZip()
    editAddress.EditCountry()
    cy.clickButtonSave()
    cy.ErrorZip('This is a required field.')
  });

  it('Edit Address Country Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.SelectCountry()
    cy.clickButtonSave()
    cy.ErrorCountry('Please select an option.')
  });

  it.only('Empty Field - Negative', () => {
    editAddress.textEditAddress()
    editAddress.ClearFirstName()
    editAddress.ClearLastName()
    editAddress.ClearCompany()
    editAddress.ClearTelephone()
    editAddress.ClearStreet1()
    editAddress.ClearStreet2()
    editAddress.ClearStreet3()
    editAddress.ClearCity()
    editAddress.ClearRegion()
    editAddress.ClearZip()
    editAddress.SelectCountry()
    cy.clickButtonSave()
    cy.ErrorFirstName('This is a required field.')
    cy.ErrorLastName('This is a required field.')
    cy.ErrorTelephone('This is a required field.')
    cy.ErrorStreet1('This is a required field.')
    cy.ErrorCity('This is a required field.')
    cy.ErrorZip('This is a required field.')
    cy.ErrorCountry('Please select an option.')
  });
});