import editAddress from '../support/pageObjects/editAddress';

describe('Edit Address Validation', () => {
  beforeEach(() => {
    cy.visit('')
    cy.loginEdit('kelompok_8@gmail.com', 'Sanbercodekelompok8')
    editAddress.clickDropDown()
    editAddress.clickMyAccount()
    editAddress.textAddressBook()
    editAddress.clickEditAddress()
  });

  it('Edit Address Success', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName()
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.VerifySuccess()
  });
  
  it('Edit Address First Name Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.ClearFirstName()
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorFirstName()
  });
  
  it('Edit Address Last Name Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName()
    editAddress.ClearLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorLastName()
  });
  
  it('Edit Address Company Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.ClearCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.VerifySuccess()
  });
  
  it('Edit Address Phone Number Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.ClearTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorTelephone()
  });
  
  it('Edit Address Street Address Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.ClearStreet1()
    editAddress.ClearStreet2()
    editAddress.ClearStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorStreet1()
  });

  it('Edit Address City Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.ClearCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorCity()
  });

  it('Edit Address State/Province Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.ClearRegion()
    editAddress.EditZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.VerifySuccess()
  });

  it('Edit Address Zip/Postal Code more than 5 - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.MoreThanZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.VerifySuccess()
  });

  it('Edit Address Zip/Postal Code Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.ClearZip()
    editAddress.EditCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorZip()
  });

  it('Edit Address Country Empty - Negative', () => {
    editAddress.textEditAddress()
    editAddress.EditFirstName() 
    editAddress.EditLastName()
    editAddress.EditCompany()
    editAddress.EditTelephone()
    editAddress.EditStreet1()
    editAddress.EditStreet2()
    editAddress.EditStreet3()
    editAddress.EditCity()
    editAddress.EditRegion()
    editAddress.EditZip()
    editAddress.SelectCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorCountry()
  });

  it('Empty Field - Negative', () => {
    editAddress.textEditAddress()
    editAddress.ClearFirstName()
    editAddress.ClearLastName()
    editAddress.ClearCompany()
    editAddress.ClearTelephone()
    editAddress.ClearStreet1()
    editAddress.ClearStreet2()
    editAddress.ClearStreet3()
    editAddress.ClearCity()
    editAddress.ClearRegion()
    editAddress.ClearZip()
    editAddress.SelectCountry()
    editAddress.clickButtonSave()
    editAddress.ErrorFirstName()
    editAddress.ErrorLastName()
    editAddress.ErrorTelephone()
    editAddress.ErrorStreet1()
    editAddress.ErrorCity()
    editAddress.ErrorZip()
    editAddress.ErrorCountry()
  });
});