import homePage from "../support/pageObjects/homePage"
import checkout from "../support/pageObjects/proceedCheckout"
import shipping from "../support/pageObjects/shippingAndPayment"

describe('Proceed to Checkout', () => {
  beforeEach(() => {
    // Mengunjungi halaman utama Magento
    cy.visit('')
  })

  it('Checkout Without Login',() =>{
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    shipping.verifyOrderSummary()
    shipping.shippingInput()
    shipping.nextToPayment()    
    checkout.wait()
    shipping.verifyBeforePayment()
    checkout.wait()
    shipping.payment()
    checkout.wait()
    shipping.verifyAfterPayment()
  })

  it('Checkout Without Login Not US',() =>{
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    shipping.verifyOrderSummary()
    shipping.shippingInputNotUS()
    shipping.nextToPayment()
    checkout.wait()
    shipping.verifyBeforePayment()
    checkout.wait()
    shipping.payment()
    checkout.wait()
    shipping.verifyAfterPayment()
  })

  it('Checkout With Login',() =>{
    cy.fixture("user.json").then((user) => {
      cy.loginEdit(user.email, user.password)
    })
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    // shipping.verifyOrderSummary()
    shipping.nextToPayment()
    checkout.wait()
    shipping.verifyBeforePayment()
    checkout.wait()
    shipping.payment()
    checkout.wait()
    shipping.verifyAfterPayment()
  })

  it('Checkout Without Login + Edit Shipping',() =>{
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    shipping.verifyOrderSummary()
    shipping.shippingInput()
    shipping.nextToPayment()
    checkout.wait()
    shipping.verifyBeforePayment()
    shipping.editShippingAddress()
    shipping.nextToPayment()
    checkout.wait()
    shipping.verifyBeforePayment()
    checkout.wait()
    shipping.payment()
    checkout.wait()
    shipping.verifyAfterPayment()
  })

  it('Checkout Without Data Shipping',() =>{
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    shipping.verifyOrderSummary()
    shipping.nextToPayment()
    shipping.validateShippingAddress()
    checkout.wait()
    cy.get(':nth-child(1) > :nth-child(1) > .radio').click()
    shipping.nextToPayment()
    shipping.validateEmailNull()
    shipping.validateDataNull()
  })

  it('Checkout With No Valid Email',() =>{
    checkout.selectProduct()
    checkout.wait()
    checkout.selectSize()
    checkout.selectColor()
    checkout.addToCart()
    checkout.validateAddToChart()
    checkout.toCart()
    checkout.wait()
    checkout.verifyProduct()
    checkout.checkout()
    shipping.verifyOrderSummary()
    shipping.nextToPayment()
    shipping.validateShippingAddress()
    shipping.shippingInputNoValidEmail()
    checkout.wait()
    shipping.nextToPayment()
    shipping.validateEmailFormat()
  })

})
